name: DEMO
on: [push] 

env:
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  #DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: image
  TAG : "1.0"
jobs:
  push-image-to-docker-hub:  
    runs-on: ubuntu-latest  
    steps:
    
    - name : Checkout Repo
    - uses: actions/checkout@v2 

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image # push The image to the docker hub
      run: docker build -t $DOCKER_USER/$REPO_NAME:$TAG .
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:$TAG
